# Generated by Django 3.2 on 2021-12-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211213_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nacional',
            new_name='national',
        ),
    ]
