# Generated by Django 3.2 on 2021-12-20 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_nacional_product_national'),
        ('user_utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHistory',
            new_name='History',
        ),
    ]
