# Generated by Django 3.2 on 2021-12-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_nacional_product_national'),
        ('user_utils', '0002_rename_userhistory_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', unique=True),
        ),
    ]
